server_url: https://86.109.15.131:6443
token: token
os:
  ssh_authorized_keys:
  - github:guangbochen
  password: passwd
install:
  mode: join
  mgmt_interface: eth0
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-amd64.iso
  tty: ttyS1,115200n8

