token: token
os:
  hostname: harv1
  ssh_authorized_keys:
    - github:guangbochen
  password: passwd
install:
  mode: create
  mgmt_interface: eth0
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-amd64.iso
  tty: ttyS1,115200n8

